# Generated by Django 5.0.6 on 2024-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0002_category_mail_settings_remove_post_file_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(),
        ),
    ]
