# Generated by Django 5.0.6 on 2024-07-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0008_alter_contacts_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
