# Generated by Django 5.0.6 on 2024-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0009_contacts_email_alter_contacts_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
