# Generated by Django 5.0.6 on 2024-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0010_alter_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='purpose',
            field=models.CharField(choices=[('Business', 'Business Proposal'), ('Personal', 'Personal Proposal'), ('Hello', 'Want to Say Hello')], max_length=50),
        ),
    ]
