# Generated by Django 5.0.6 on 2024-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0011_alter_contacts_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='purpose',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior')], max_length=50),
        ),
    ]
