# Generated by Django 5.0.6 on 2024-07-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0012_alter_contacts_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
