# Generated by Django 5.0.6 on 2024-07-13 19:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0013_alter_contacts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='cat_name'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='purpose',
            field=models.CharField(max_length=50),
        ),
    ]
